#!/usr/bin/env ruby

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

remote_name = ARGV[0]
remote_url = ARGV[1]

my_github_url_http = "https://github.com/KevinCorcoran"
my_github_url_ssh  = "git@github.com:KevinCorcoran"

unless remote_url.start_with?(my_github_url_http) or remote_url.start_with?(my_github_url_ssh)
	puts "pre-push hook preventing push to remote '#{remote_name}' " +
	     "because its URL does not start with #{my_github_url}"
	puts "You can bypass this with 'git push --no-verify'"
	exit 1
end

